version: "3"

services:
  tmail-frontend:
    image: linagora/tmail-web:v0.13.1
    container_name: tmail-frontend-testing
    ports:
      - "8080:80"
    volumes:
      - ./configuration/tmail-web/env.file:/usr/share/nginx/html/assets/env.file
    networks:
      - tmail
#    depends_on:
#      - tmail-backend
#
#  tmail-backend:
#    image: linagora/tmail-backend:memory-branch-master
#    container_name: tmail-backend-testing
#    volumes:
#      - ./configuration/tmail-backend/jwt_publickey:/root/conf/jwt_publickey
#      - ./configuration/tmail-backend/jwt_privatekey:/root/conf/jwt_privatekey
#      - ./configuration/tmail-backend/mailetcontainer.xml:/root/conf/mailetcontainer.xml
#      - ./configuration/tmail-backend/imapserver.xml:/root/conf/imapserver.xml
#    ports:
#      - "80:80"
#      - "8000:8000"
#      - "25:25"
#      - "143:143"
#    environment:
#      - DOMAIN=domain.tld
#    networks:
#      - tmail

networks:
  tmail:
